/* 
 * eToro Metadata API
 *
 * The metadata API provides basic meta data for the eToro system. The metadata is comprised of reference tables for all the other end-points in this API
 *
 * OpenAPI spec version: 1.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */
using System;
using System.IO;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.Reflection;
using RestSharp;
using NUnit.Framework;

using IO.Swagger.Client;
using IO.Swagger.Api;

namespace IO.Swagger.Test
{
    /// <summary>
    ///  Class for testing DefaultApi
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the API endpoint.
    /// </remarks>
    [TestFixture]
    public class DefaultApiTests
    {
        private DefaultApi instance;

        /// <summary>
        /// Setup before each unit test
        /// </summary>
        [SetUp]
        public void Init()
        {
            instance = new DefaultApi();
        }

        /// <summary>
        /// Clean up after each unit test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of DefaultApi
        /// </summary>
        [Test]
        public void InstanceTest()
        {
            // TODO uncomment below to test 'IsInstanceOfType' DefaultApi
            //Assert.IsInstanceOfType(typeof(DefaultApi), instance, "instance is a DefaultApi");
        }

        /// <summary>
        /// Test GetAssetClasses
        /// </summary>
        [Test]
        public void GetAssetClassesTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //instance.GetAssetClasses();
            
        }
        /// <summary>
        /// Test GetCandlePeriod
        /// </summary>
        [Test]
        public void GetCandlePeriodTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //instance.GetCandlePeriod();
            
        }
        /// <summary>
        /// Test GetCountries
        /// </summary>
        [Test]
        public void GetCountriesTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //instance.GetCountries();
            
        }
        /// <summary>
        /// Test GetExchanges
        /// </summary>
        [Test]
        public void GetExchangesTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //instance.GetExchanges();
            
        }
        /// <summary>
        /// Test GetInstruments
        /// </summary>
        [Test]
        public void GetInstrumentsTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string instrumentIds = null;
            //instance.GetInstruments(instrumentIds);
            
        }
        /// <summary>
        /// Test GetSectors
        /// </summary>
        [Test]
        public void GetSectorsTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //instance.GetSectors();
            
        }
        /// <summary>
        /// Test GetStatsPeriods
        /// </summary>
        [Test]
        public void GetStatsPeriodsTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //instance.GetStatsPeriods();
            
        }
    }

}
