# coding: utf-8

# flake8: noqa
"""
    eToro System API

    The System API provides general data on the full eToro System  # noqa: E501

    OpenAPI spec version: 1.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

# import models into model package
