# coding: utf-8

"""
    User

    The User API provides data on a user including trading statistics  # noqa: E501

    OpenAPI spec version: 1.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from api.default_api import DefaultApi  # noqa: E501
from swagger_client.rest import ApiException


class TestDefaultApi(unittest.TestCase):
    """DefaultApi unit test stubs"""

    def setUp(self):
        self.api = api.default_api.DefaultApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_get_aggregates_history(self):
        """Test case for get_aggregates_history

        Trade/History/Aggregates  # noqa: E501
        """
        pass

    def test_get_copiers_history(self):
        """Test case for get_copiers_history

        Copiers/History  # noqa: E501
        """
        pass

    def test_get_copy_simulation_data(self):
        """Test case for get_copy_simulation_data

        CopySimulation  # noqa: E501
        """
        pass

    def test_get_daily_gain(self):
        """Test case for get_daily_gain

        Daily Gain  # noqa: E501
        """
        pass

    def test_get_gains(self):
        """Test case for get_gains

        Monthly Gain  # noqa: E501
        """
        pass

    def test_get_live_copiers(self):
        """Test case for get_live_copiers

        Copiers/Live  # noqa: E501
        """
        pass

    def test_get_live_risk_score(self):
        """Test case for get_live_risk_score

        RiskScore/Live  # noqa: E501
        """
        pass

    def test_get_risk_history(self):
        """Test case for get_risk_history

        RiskScore/History  # noqa: E501
        """
        pass

    def test_get_user_discovery_data(self):
        """Test case for get_user_discovery_data

        Discovery  # noqa: E501
        """
        pass

    def test_get_user_followers(self):
        """Test case for get_user_followers

        Social/Followers  # noqa: E501
        """
        pass

    def test_get_user_info(self):
        """Test case for get_user_info

        Info  # noqa: E501
        """
        pass

    def test_get_user_portfolio_summary(self):
        """Test case for get_user_portfolio_summary

        PortfolioSummary  # noqa: E501
        """
        pass

    def test_get_user_visual_portfolio(self):
        """Test case for get_user_visual_portfolio

        VisualPortfolio  # noqa: E501
        """
        pass

    def test_get_users_discovery_data(self):
        """Test case for get_users_discovery_data

        Multiple Discovery  # noqa: E501
        """
        pass

    def test_get_users_info(self):
        """Test case for get_users_info

        Multiple Info  # noqa: E501
        """
        pass

    def test_get_users_visual_portfolio(self):
        """Test case for get_users_visual_portfolio

        Multiple Visual Portfolio  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
