# coding: utf-8

# flake8: noqa
"""
    User

    The User API provides data on a user including trading statistics  # noqa: E501

    OpenAPI spec version: 1.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

# import models into model package
