# coding: utf-8

# flake8: noqa

"""
    eToro Discovery API

    The discovery API allows you to discover customers in the eToro network. It is important to note that only customers who have opted-in for discovery will be shown by this API  # noqa: E501

    OpenAPI spec version: 1.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

# import apis into sdk package
from etoro_api.api.default_api import DefaultApi
# import ApiClient
from etoro_api.api_client import ApiClient
from etoro_api.configuration import Configuration
# import models into sdk package
