# coding: utf-8

"""
    eToro Discovery API

    The discovery API allows you to discover customers in the eToro network. It is important to note that only customers who have opted-in for discovery will be shown by this API  # noqa: E501

    OpenAPI spec version: 1.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import etoro_api
from api.default_api import DefaultApi  # noqa: E501
from etoro_api.rest import ApiException


class TestDefaultApi(unittest.TestCase):
    """DefaultApi unit test stubs"""

    def setUp(self):
        self.api = api.default_api.DefaultApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_get_metadata(self):
        """Test case for get_metadata

        MetaData  # noqa: E501
        """
        pass

    def test_get_search(self):
        """Test case for get_search

        Search  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
