# coding: utf-8

"""
    eToro System API

    The System API provides general data on the full eToro System  # noqa: E501

    OpenAPI spec version: 1.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import etoro_api
from api.default_api import DefaultApi  # noqa: E501
from etoro_api.rest import ApiException


class TestDefaultApi(unittest.TestCase):
    """DefaultApi unit test stubs"""

    def setUp(self):
        self.api = api.default_api.DefaultApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_get_auto_complete(self):
        """Test case for get_auto_complete

        Auto-Complete  # noqa: E501
        """
        pass

    def test_get_daily_price_change(self):
        """Test case for get_daily_price_change

        Daily Price Change  # noqa: E501
        """
        pass

    def test_get_insights(self):
        """Test case for get_insights

        Insights  # noqa: E501
        """
        pass

    def test_get_market_events(self):
        """Test case for get_market_events

        Market Events  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
